config/routes.rb
Rails.application.routes.draw do
  root 'sessions#login'
  resources :request_accesses
  resources :documents
  resources :users

  match 'users/:id/create_request' => 'users#create_request', via: [:patch, :put, :post], as: :users_create_request
  match 'users/:id/approve_request' => 'users#approve_request', via: [:patch, :put, :post], as: :users_approve_request
  match 'users/:id/deny_request' => 'users#deny_request', via: [:patch, :put, :post], as: :users_deny_request
  match 'users/:id/view_document' => 'users#view_document', via: [:get], as: :users_view_document

  get    'login'   => 'sessions#login', :as => :loginpage
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'signup' => 'sessions#signup', :as => :signup
  post 'sessions/new_user' => 'sessions#new_user'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document
  include Mongoid::Document
  include Mongoid::Timestamps

  embedded_in :user

  field :url, type: String
  field :file_name, type: String
  field :type, type: String
end

app/models/request_access.rb
class RequestAccess
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :requestor, class_name: 'User'
  belongs_to :grantor, class_name: 'User'

  field :status, type: String, default: 'pending'

  validates :status, :inclusion => { :in => %w(pending approved denied) }
  validates_uniqueness_of :requestor_id, scope: :grantor_id

  # TODO: Send Email notification to requestor on status change
  def send_email
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :username, type: String
  field :email, type: String
  field :type, type: String
  field :encrypted_password, type: String

  embeds_many :documents, class_name: "Document"

  validates :type, :inclusion => { :in => %w(patient doctor pharmacist) }
  validates :username, presence: true
  validates :email, presence: true

  validates_uniqueness_of :email

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :verify_login

  def verify_login
    if !logged_in?
      redirect_to login_path
    end
  end

end

app/controllers/sessions_controller.rb
require 'digest/sha1'

class SessionsController < ApplicationController

  skip_before_action :verify_login

  def login
  end

  def create
    encrypted_password = Digest::SHA1.hexdigest(params[:session][:password]) rescue nil
    user = User.where(email: params[:session][:email].downcase, encrypted_password: encrypted_password).first rescue nil
    if user
      log_in user
      redirect_to user
    else
      @error_msg = "Invalid username or password"
      render 'login'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end

  def signup
    @user = User.new
    render 'sessions/signup'
  end

  def new_user
    encrypted_password= Digest::SHA1.hexdigest(user_params[:password])
    @user = User.new(username: user_params[:username], encrypted_password: encrypted_password, type: user_params[:type], email: user_params[:email])
    begin
      if @user.save!
        redirect_to login_path
      end
    rescue
      render 'signup'
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    if @user.type == "doctor" || @user.type == "pharmacist"
      @patients_requested = RequestAccess.where(requestor_id: @user._id)
      @patients_not_requested = User.where(:type => "patient", :_id.nin => @patients_requested.pluck(:grantor_id))
    elsif @user.type == "patient"
      @requestors = RequestAccess.where(grantor_id: @user._id, :status => "pending")
    end
  end

  def create_request
    @request_access = RequestAccess.create(requestor_id: params[:id], grantor_id: params[:patient_id])
    @user = User.find(params[:id])
    redirect_to @user
  end

  def approve_request
    @request_access = RequestAccess.where(grantor_id: params[:id], requestor_id: params[:requestor_id]).first
    @request_access.status = "approved"
    @request_access.save!
    @user = User.find(params[:id])
    redirect_to @user
  end

  def deny_request
    @request_access = RequestAccess.where(grantor_id: params[:id], requestor_id: params[:requestor_id]).first
    @request_access.status = "denied"
    @request_access.save!
    @user = User.find(params[:id])
    redirect_to @user
  end

  def view_document
    @user = User.find(params[:id])
    @documents = User.where(id: params[:patient_id]).first.documents
    @documents = @documents.where(type: "prescription") if @user.type == 'pharmacist'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :type, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def load_profile
    redirect_to home_path
  end

  def back_url
    session[:previous_url]
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/request_accesses_helper.rb
module RequestAccessesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user = @current_user || User.find(session[:user_id]) rescue nil
  end

  def logged_in?
    @current_user = current_user
    !@current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PharmeasyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%#= form.text_field :type, id: :user_type %>
    <%= form.select :type, ['patient', 'doctor', 'pharmacist'], id: :user_type %>
  </div>


  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <div class="card">
    <div class="card-header">
      <h5 style="display: inline-block;">Profile Details</h5>
      <span style="float: right; display: inline-block;"><a><%= link_to 'Logout', logout_path, method: :delete, class: "btn btn-danger btn-sm" %></a></span>

    </div>
    <div class="card-body">
      <h5 class="card-title">Hello <%= @user.username.capitalize %>,</h5>
      <br/>
      <h4 class="card-text" style="text-decoration: underline">Basic Details: </h4>
      <p class="card-text">Email: <%= @user.email %></p>
      <p class="card-text">Role: <%= @user.type.capitalize %></p>

    </div>
  </div>

  <br/><br/>

  <% if ['doctor', 'pharmacist'].include? @user.type %>
    <h3>Patients: </h3>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Status</th>
        <th colspan="1"></th>
      </tr>
      </thead>

      <tbody>
      <% @patients_not_requested.each do |patient| %>
        <tr>
          <td><%= patient.username %></td>
          <td><%= patient.email %></td>
          <td><%= link_to "Request Records", users_create_request_path({:user_id => @user.id.to_s, :patient_id => patient.id.to_s}), method: :post %></td>
          <td></td>
        </tr>
      <% end %>
      <% @patients_requested.each do |patient| %>
        <tr>
          <td><%= patient.grantor.username %></td>
          <td><%= patient.grantor.email %></td>
          <% if patient.status == 'approved' %>
            <td><span class="badge badge-success"><%= patient.status.capitalize %></span></td>
          <% elsif patient.status == 'pending' %>
            <td><span class="badge badge-info"><%= patient.status.capitalize %></span></td>
          <% elsif patient.status == 'denied' %>
            <td><span class="badge badge-danger"><%= patient.status.capitalize %></span></td>
          <%end%>
          <% if patient.status == "approved" %>
            <td><%= link_to "View Documents", users_view_document_path({:user_id => @user.id.to_s, :patient_id => patient.grantor.id.to_s}), method: :get %></td>
          <% end %>
          <td></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>

  <% if @user.type == 'patient' %>
    <h3>Requests Pending for Approval:</h3>
    <table class="table table-striped">
      <thead>
      <tr>
        <th class="field">Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Status</th>
        <th colspan="1"></th>
      </tr>
      </thead>

      <tbody>
      <% @requestors.each do |requestor| %>
        <tr>
          <td><%= requestor.requestor.username %></td>
          <td><%= requestor.requestor.email %></td>
          <td><%= requestor.requestor.type.capitalize %></td>
          <td><%= link_to "Approve", users_approve_request_path({:user_id => @user.id.to_s, :requestor_id => requestor.requestor.id.to_s}), method: :put %></td>
          <td><%= link_to "Reject", users_deny_request_path({:user_id => @user.id.to_s, :requestor_id => requestor.requestor.id.to_s}), method: :put %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/users/view_document.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h3>Documents</h3>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Url</th>
      <th>File name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.url %></td>
        <td><%= document.file_name %></td>
        <td><%= document.type %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <div class="btn btn-secondary"><%= link_to 'Back', @user, :style => "color: white" %></div>
</div>